version: 2
jobs:
    build:
        working_directory: '~/workspace'
        docker:
            - image: 'circleci/php:7.2'
        steps:
            - checkout
            - run:
                name: 'Setup environment'
                command: |
                    cp .env.dist .env
            - run:
                name: 'Install Composer Dependencies'
                command: |
                    composer install

