version: 2
jobs:
    build:
        docker:
            - image: 'circleci/php:7.2'
        steps:
            - run:
                name: 'Install Composer Dependencies'
                command: |
                    composer install

