version: 2
jobs:
    build:
        docker:
            - image: php:7.2-apache
        steps:
            - run:
                name: Run Composer install
                command: |
                    composer install

