version: 2
jobs:
    build:
        working_directory: '~/workspace'
        docker:
            - image: 'php:7.2-apache'
        steps:
            - run:
                name: 'Install Composer Dependencies'
                command: |
                    composer install

