#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: 'App\Controller\SecurityController:loginAction'

secured_area:
    path: /secured
    methods: [GET]
    defaults:
        _controller: 'App\Controller\DefaultController:securedAction'

connect:
    path: /connect
    methods: [GET, POST]
    defaults:
        _controller: 'App\Controller\SecurityController:connectAction'

logout:
    path: /logout
    methods: [GET]
